name: Github Action for curl
uses: wei/curl@v1.1.1

on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST https://uploader.codecov.io/latest/linux/codecov