name: Codecov Test
on: [push]
jobs:
  Codecov-Test:
    name: Codecov Test Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Run NPM test
      run: |
        npm test -- --coverage
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./clover.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        # fail_ci_if_error: true # optional (default = false)
        directory: ./coverage #optional
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true # optional (default = false)

      